### PR TITLE
Event sender modification

### LINKED ISSUE #115: event_sender wrong event calculation
# Event sender sends double the event asked

## Description: 
* When giving the parameter -c 25 -b 2, the total of the event sent is 100. 
* This is the same for other combination of numbers
* The number of event displayed on the front end is corresponding to the double amount of events expected. 

## How to reproduce the bug:
* run the event_sender giving any -c and -b parameters combined-
* Observe that the total event number is doubled in the console, but also in the frontend

## Screenshots:
Screenshot 2022-10-21 at 15 34 47

We can take a look at it since we are working on the generator anyway, if it's okay with you guys?

### PR DESCRIPTION
**Pull request by alrapal**
origin ItJustWorksBetterTM/EiffelVis#22 with discussions

# Event Sender Modification 

## Description: 
  * Added Eiffel event list to the generator to allow for random event types
  * Added information on the README on how to connect event_sender / rabbitmq / backend
  * Changed the maximum amount of links per event to allow for a more realistic graph 
  * Added CLI arguments to allow for control over runtime and latency between events sent  
    * Arguments added: 

  | Argument name| Short name | Description | Default value|
  | ------------- | ------------- | ------------- | ------------- |
  | total_duration  | -t  | Total amount of time in milliseconds for the generator to run  |  3 600 000   |
  | min_latency  | -m  | Minimum value for the range of latency between events sent   |  5  |
  | latency_max  | -l  | Maximum value for the range of latency between events sent   |  220  |

## Useful notes:
* The default values of the CLI arguments (count, total_duration, min_latency and latency max ) are set to mimic roughly 30 000 events set per hour.
* The generator will run until either the count (total events to be sent) or the total_duration (duration for generator to run) has been reached.

## Screenshots:
Preview of random event types with random links:

Screenshot 2022-10-14 195140

resolves #115

### CODE REVIEW

**Comment by RuthgerD** [comment]
Would like to see this first: https://github.com/ItJustWorksBetterTM/EiffelVis/pull/44

File: backend/tools/event_sender/src/main.rs [hunk 1]
```diff
@@ -2,24 +2,39 @@ use std::{
...
     event_set::{Event, EventSet, Link},
     generator::EventGenerator,
 };
+
 use lapin::{options::*, BasicProperties, Connection, ConnectionProperties};
 
 use clap::Parser;
 use rand::{thread_rng, Rng};
 
+const EVENT_TYPES: [&str; 23] = [
```
Comment (RuthgerD) [inline backend/tools/event_sender/src/main.rs:18]: Can we put everything related to the EventSet in its own dedicated file?
As I mentioned in #14 making a zst type that implements From<> would be nice.

```rust
pub struct EIffelVocabulary;

const EVENT_TYPES: [&str; 23] = [
    "ActC", "ActF", "ActS", "ActT", "AnnP", "ArtC", "ArtP", "ArtR", "TCC", "TCF", "TCS", "TCT",
    "TERCC", "TSF", "TSS", "CD", "CLM", "ED", "FCD", "ID", "IV", "SCC", "SCS",
];

impl From<EIffelVocabulary> for EventSet {
    fn from(_: EIffelVocabulary) -> Self {
        let mut builder = EventSet::build();

        for eventtype in EVENT_TYPES {
            // Initialize and create the event variable
            let mut event = Event::new(eventtype.to_string(), "1.0.0");

            // Create the random number generate for the links
            let _randomrange = rand::thread_rng().gen_range(1..3);

            // Loop and add the links to the event
            for linknumber in 0.._randomrange {
                event = event.with_link(format!("Link{linknumber}"));
            }

            builder = builder.add_event(event);
        }

        builder
            .add_link(Link::new("Link0", true))
            .add_link(Link::new("Link1", true))
            .add_event(
                Event::new("Event", "1.0.0")
                    .with_link("Link0")
                    .with_link("Link1"),
            )
            .build()
            .expect("This should work")
    }
}

```

then in the main.rs file:

```rust
let gen = EventGenerator::new(
        cli.seed.unwrap_or_else(|| thread_rng().gen::<usize>()),
        4,
        8,
        EIffelVocabulary.into()
    );
```

**Review by RuthgerD — CHANGES_REQUESTED** [review]

**Comment by alrapal** [comment]
> Would like to see this first: [ItJustWorksBetterTM#44](https://github.com/ItJustWorksBetterTM/EiffelVis/pull/44)

OK! We will add the bug fix to this PR then =)

File: backend/tools/event_sender/src/main.rs (hunk 1 above)
Comment (alrapal) [reply backend/tools/event_sender/src/main.rs:18]: We will try to do this this week, depending on the schedule!

Comment (gusaxtcha) [reply backend/tools/event_sender/src/main.rs]: Added the changes suggested.

File: backend/crates/eiffelvis_gen/src/eiffel_vocabulary.rs [hunk 2]
```diff
@@ -0,0 +1,42 @@
+use crate::event_set::{Event, EventSet, Link};
+
+use rand::Rng;
+
+pub struct EiffelVocabulary;
+
+const EVENT_TYPES: [&str; 23] = [
+    "ActC", "ActF", "ActS", "ActT", "AnnP", "ArtC", "ArtP", "ArtR", "TCC", "TCF", "TCS", "TCT",
```
Comment (RuthgerD) [inline backend/crates/eiffelvis_gen/src/eiffel_vocabulary.rs:8]: Think this change undid the event type renames

Comment (gusaxtcha) [reply backend/crates/eiffelvis_gen/src/eiffel_vocabulary.rs:8]: Probably a consequence on working on this late in the evening :( Thanks for catching it!

File: README.md [hunk 3]
```diff
@@ -74,3 +74,21 @@ To contribute to this repository, please see the [contribution guidelines](./CON
 If you would like to read more about the algorithm used by EiffelVis, please see the [algorithm concept](./frontend/README.md#layout-algorithm).
 
 Copyright © 2022, EiffelVis. EiffelVis is a product by ItJustWorks™.
+
+# Testing
+
+TODO
```
Comment (RuthgerD) [inline README.md:80]: Lets not kid ourselves, TODOs are an eternal blight on your legacy

File: backend/tools/event_sender/src/main.rs [hunk 4]
```diff
@@ -72,22 +84,14 @@ async fn app() -> anyhow::Result<()> {
 
     let channel_a = conn.create_channel().await?;
 
+    // println!(?queue, "Declared queue");
```
Comment (RuthgerD) [inline backend/tools/event_sender/src/main.rs:87]: remove

**Review by RuthgerD — CHANGES_REQUESTED** [review]
Just need to remove some extra text and we can merge :)

File: README.md (hunk 3 above)
Comment (alrapal) [reply README.md:80]: 🤣 Fait, fair!

File: backend/tools/event_sender/src/main.rs (hunk 4 above)
Comment (alrapal) [reply backend/tools/event_sender/src/main.rs:87]: will do!

**Comment by RuthgerD** [comment]
Would be nice if https://github.com/ItJustWorksBetterTM/EiffelVis/pull/46 was included here

File: backend/tools/event_sender/src/main.rs [hunk 5]
```diff
@@ -16,10 +15,18 @@ use rand::{thread_rng, Rng};
...
-    #[clap(default_value = "1", short, long)]
+    // NOTE: The number of events along with the total duration, min lacency and latency max is to be used for stress testing.
+    // When setting these values, keep in mind that the generator process will stop at whichever value is reached first (between the count and total duration).
+    // The defaut settings on these variables represent roughly 30,000 events sent per hour.
+
+    // Total amount of events to be sent (note: multiplied with the `burst` option)
+    #[clap(default_value = "30000", short, long)]
     count: usize,
 
+    // Total duration to run the event generator
```
Comment (RuthgerD) [inline backend/tools/event_sender/src/main.rs:26]: All these comments need to be tripple slash, otherwise it doesn't show up in the --help command:
image

**Review by RuthgerD — CHANGES_REQUESTED** [review]
Tested it out, seems useful; would like to see the fix above and the added slashes for the --help command.

File: backend/tools/event_sender/src/main.rs (hunk 5 above)
Comment (RuthgerD) [reply backend/tools/event_sender/src/main.rs]: ping me when ready, looks good to merge.

**Comment by RuthgerD** [comment]
Thanks!
